# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a834b23ab0ed56ad153f4377bd8de98adcc7d6c17b2fffa2f364e4505096e12983107e6d75fe8538d8c875f71da99f0c0aac6edd48cfeb6175c016c7cdce0e3f

test:
  secret_key_base: c12ccca2ef4c4f8ca5b7f7eb8c2ef3043e023f72812e9d624ba82a531ac6afb328fe5a7acf95d8481c2a17caa87b1960a074aea34bca140161b85f857da0c654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
